from pathlib import Path
from typing import Dict, List

from fpdf import FPDF

from app.config import EXPORTS_DIR


def clean_pdf_text(text: str) -> str:
    """
    FPDF's built-in Helvetica font does not support every Unicode
    character generated by an LLM.

    Convert unsupported characters into safe equivalents.
    """

    replacements = {
        "“": '"',
        "”": '"',
        "‘": "'",
        "’": "'",
        "—": "-",
        "–": "-",
        "…": "...",
        "•": "*",
        "→": "->",
        "←": "<-",
        "™": "(TM)",
        "©": "(C)",
        "®": "(R)",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text.encode(
        "latin-1",
        errors="replace",
    ).decode("latin-1")


class ComicPDF(FPDF):

    def header(self):
        self.set_font(
            "Helvetica",
            "B",
            16,
        )

        self.cell(
            0,
            10,
            "ComicCraft",
            align="C",
        )

        self.ln(8)


def save_pdf(
    layout: List[Dict],
    comic_id: str,
) -> str:

    pdf = ComicPDF(
        orientation="P",
        unit="mm",
        format="A4",
    )

    pdf.set_auto_page_break(
        auto=True,
        margin=15,
    )

    for panel in layout:

        pdf.add_page()

        pdf.set_font(
            "Helvetica",
            "B",
            16,
        )

        title = (
            f"Panel {panel['panel_number']}: "
            f"{panel['title']}"
        )

        pdf.multi_cell(
            0,
            10,
            clean_pdf_text(title),
        )

        pdf.ln(3)

        image_path = Path(
            panel["image_path"]
        )

        if image_path.exists():

            pdf.image(
                str(image_path),
                x=15,
                y=None,
                w=180,
            )

            pdf.ln(5)

        pdf.set_font(
            "Helvetica",
            "I",
            10,
        )

        pdf.multi_cell(
            0,
            6,
            clean_pdf_text(
                panel["scene_description"]
            ),
        )

        pdf.ln(4)

        pdf.set_font(
            "Helvetica",
            "B",
            11,
        )

        pdf.multi_cell(
            0,
            6,
            clean_pdf_text(
                panel["caption"]
            ),
        )

        pdf.ln(3)

        pdf.set_font(
            "Helvetica",
            "",
            11,
        )

        pdf.multi_cell(
            0,
            6,
            clean_pdf_text(
                panel["narration"]
            ),
        )

        pdf.ln(3)

        pdf.set_font(
            "Helvetica",
            "B",
            11,
        )

        pdf.multi_cell(
            0,
            6,
            clean_pdf_text(
                panel["dialogue"]
            ),
        )

    output_path = (
        EXPORTS_DIR /
        f"{comic_id}.pdf"
    )

    pdf.output(
        str(output_path)
    )

    return str(output_path)
